### ISSUE TITLE
Switch rotation & QOL improvements

### ISSUE THREAD

**Issue by JellyTitan** [daneski13/Junco#1]
If nobody has started that yet, I'd like to give it a go. 

There's some other QOL improvements i'd like to add:
* Through-hole/smd hybrid footprints. (I struggle with the SOD123 package, through holes are just my personal preference)
* Swap the MX hotswop footrprint for a combo MX/Choc v1/Choc V2 footprint. (Specifically, the ones found in [chunky 2040 rev2](https://github.com/freznel10/Chunky2040_rev2))
* Add GND VCC planes to simplify routing. 
* Rotate the LEDs for a consistent orientation. (This complicates routing, but really helps with the build when your brain is on autopilot)
* On the thumb cluster, move the level shifter and underglow down a bit so they don't interfere with choc V2 MX keycaps.

Thoughts?

**Comment by daneski13** [comment]
I've been absolutely swamped with my classes this semester, so I'd really appreciate knocking stuff off the to-do list! 

Very pro through-hole option for the diodes, I've gotten pretty good at soldering those little buggers at this point but man is it still a frustrating pain in the ass sometimes.

Rotating the switches is on the top of my [to-do](https://github.com/Daneski13/Junco/blob/main/CONTRIBUTING.md). It was a complete oversight that I didn't realize until I started soldering and somehow escaped the people who reviewed the PCB as well. Should be as easy as pressing "R" a couple times on each footprint (thumb keys might need some more finesse to ensure they stay in the same position if they were to be rotated as well), I just haven't had the time to re-route everything. If you were to undertake that feel free to route any way you see fit assuming the key and LED matrices stay the same.

Also, hardware level handedness would be a nice QOL improvement (pull an unused pin on the left side high and the corresponding pin on the right side low).

I'm sort of against using a combo Choc/MX footprint, non-goal in [philosophy](https://github.com/Daneski13/Junco#philosophy)) for the reason "MX switches should use MX spacing, Choc switches should use Choc spacing." Unless there's a lot more people than I'm aware of actually using Choc switches with MX spacing? I've thought about creating a more "portable" variant that uses Choc spacing and either ditches the rotary encoders or uses smaller profile SMD encoders, just haven't had time to devise that yet.

On your last point I should note that pretty much all of the soldering is on the backside of the PCB (including the Picos unless you put the pico upside-down on the frontside), so nothing should interfere with keycaps, but feel free to move that level shifter around if you'd like to simplify routing or whatnot. On that note, since the SMD diodes are soldered on the backside it probably makes since for the through-hole diode option to allow for placement under the keycaps.

**Comment by JellyTitan** [comment]
Sounds good! I've started. 
There's some interesting techniques used here - like the LED footprint offset from zero. 
I've put in the through-hole diodes. You mentioned all the soldering is done on the back. If the through hole diodes are used, then there will be components on the front and back. I'd like to propose soldering the through holes on the front, so that all components will be on the back. (I like to pull the solder mask on one side for those, so they can only be soldered in one way only - sort of a dirty poka-yoke)

Still working on the wiring and handedness pins.
I'll respect your MX/Choc spacing standard. (The choc v2 MX keys are hardly ever used - so i like to promote them when i can)

**Comment by daneski13** [comment]
Sounds good!

Yah the LED footprint offset just made it way easier to ensure they always had the right distance from the switch center.

**Comment by JellyTitan** [comment]
I've got the basic rebuild done on branch key_rotation:
https://github.com/JellyTitan/Junco/tree/key_rotation

It still needs some code/doc/footprint cleanup work.

I'm putting together a pick and place config along with a BOM. I've never used PCB assembly before and want to try it out. I'm electrically 'not great'. (Electricity is magic and it scares me). 
Any thoughts on which component would be best for the level shifter?
https://jlcpcb.com/parts/componentSearch?searchTxt=SN74AHCT1G125

**Comment by daneski13** [comment]
The VCC and GND planes make the routing way cleaner! Great work!

SN74AHCT1G125DBVR would be the proper choice I think, appears to be nearly identical to the SN74AHCT1G125DBVT model I recommend off of aliexpress. only difference from the datasheet looks like the wholesale minimum order quantity, so I would assume the DBVR has somewhat looser tolerances (which really isn't a concern for us). 

I've never used PCB-parts assembly before either, since I've only done really small batches where a few hours soldering was a decent tradeoff to save money. Also, I wanted to use SK6803s over SK6812s so no need to force a lower the brightness for the LEDs.

**Comment by daneski13** [comment]
I should note that there are a lot of hole clearance violations relating to a bunch of your vias that board manufucturers will not like (I set the hole clearances to JLCPCB's parameters for vias, you can safely ignore hole clearance issues for non-via holes)

**Comment by JellyTitan** [comment]
Thanks for catching that!
I imported the JLCPCB config from this template repo:
https://github.com/sethhillbrand/kicad_templates

I then increased some stuff from the minimums and re-audited everything.
When you mention hole clearance issues - is it specifically the `copper to hole clearance`?
![junco_drc_jlcpcb](https://user-images.githubusercontent.com/72168556/236938267-1c22ea1c-54ac-4241-9df7-72bb7a98e264.png)

**Comment by daneski13** [comment]
No, clearance between tracks and vias is set manually with a custom rule. It's set at the proper 0.254mm, the “copper to hole clearance" rule has no effect on vias within the constraints tab:

```
(rule VIA_CLEAR_TO_TRACK
   (constraint clearance (min "0.254mm"))
   (condition "A.Type == 'Via' && B.Type == 'Track'"))
```

What I was referring to was `hole to hole clearance` which I had set at 0.5mm, which is the proper hole to hole clearance for Different nets on JLCPCB, considering it's extremely unlikely you would have vias or holes part of the same net anywhere near each other on a decently designed keyboard PCB I went with 0.5. 0.254 is only the correct hole to hole clearance for vias of the  _same net_ which is why I had it set at 0.5.

I was also thinking of the DRC errors related to the holes on the LED footprint, for whatever reason I assumed those were vias and chalked it up to a clearance issue when in actuality it's an issue with the minimum drill hole size (`minimum through hole` constraint). For 1&2 layer PCBs the minimum drill hole size is 0.3mm for both through holes and vias, almost all the holes on your PCB are set to 0.25mm.

I should also note that the config your using is chopping the last decimal point on several constraints and that may cause issues . It seems that repo you pointed to is out of date as it hasn't been updated in 4 years and there's a few open issues that mention the values. 

I'll just quickly detail all of issues with it that I see in that constraint screen shot you sent:

- `minimum annular width` should be 0.13, not 0.1 (I originally had 0.2 set, no clue why, my bad)
- `copper to edge` clearance really shouldn't be 0.01, I originally had this set to 0.2 when it's sort of 0.3. JLC's guidance on this is kinda confusing since "Copper to [blank]" related to edges is 0.3mm but "Routed outline tolerance" is 0.2 with a +/- 0.1mm precision, so I think I set it to 0.2mm to make DRC sod off for the pad routes near the LED edge cuts. I'm probably going to edit the LED footprint to be a couple non plated through holes rather than edge cuts to avoid the extra routing fee anyway.
- I had originally set `copper to hole` to 0.33 since that is the proper value for plated through holes and 0.254 is the proper value for vias (0.254 is already already taken care of by custom rule as detailed)
- `hole to hole clearance` as mentioned earlier is 0.5 for different nets

Side note, the original `minimum via diameter` I set was wrong, should be 0.5 but it didn't matter since I was using 0.8mm vias, your PCB is using a 0.4mm diameter and 0.25 hole (probably my bad since that was the default KiCad constraint), it's also failing those rules you imported. I was using 0.8mm diameter, 0.4mm hole vias that I declared in the netclass for the PCB so it's interesting that they ended up at 0.4mm/0.25, pretty sure it's possible to change via sizing across the entire board with a couple clicks in some menu/dialog box so not a super big deal. Not sure exactly why I chose those 0.8/0.4 values, think I copied that from either Corne or SofleV2. 0.6mm/0.3mm or 0.7mm/0.3mm would be good for vias/PTH that connect the layers, 0.3 or bigger annular width should be fine for the 5V ~1Amp from USB. The 0.4mm hole I was using is unnecessarily big when 0.3 is the minimum.

All constraints: [https://jlcpcb.com/capabilities/pcb-capabilities ](https://jlcpcb.com/capabilities/pcb-capabilities )
Extra costs: [https://support.jlcpcb.com/article/62-what-cases-will-be-charged-of-extra-cost](https://support.jlcpcb.com/article/62-what-cases-will-be-charged-of-extra-cost)

I'm kinda tempted to make my own complete template/rule set for JLCPCB 2 layer PCBs, didn't really realize that was a gaping hole in the community. Assumed everyone just did it themselves on personal preference and the constraints of their preferred manufacturing house.

**Comment by JellyTitan** [comment]
I'm still working on the changes you suggested, along with removing vias from smd pads. (It's worked for me in the past, but it's considered sloppy, and i don't want to be sloppy).

I wanted to jot some stuff down before i forget:

I'd really like to see an updated jlc template! There is a ton of forum threads debating what jlc's real specs are, and what you can get away with. I've had really good luck cribbing specs from other popular board repos. I haven't had a board rejected yet - but it totally makes sense to dial everything down to the lowest common denominator manufacturing spec wise, so it could be produced anywhere. (Plus I've always been sloppy with my specs, this is a good learning experience).

As for the extra manufacturing costs - I've been charged that a few times, twice for [Sofle switch plates](https://github.com/JellyTitan/SofleKeyboard/blob/master/docs/images/IMG_20191104_202757.jpg), and never for the Sofle board itself. I also got that extra hole charge for [this monstrosity](https://github.com/JellyTitan/Cantor-Master-Key/blob/main/assets/CantorChocV2_V1.4.png), but that seems pretty reasonable. 

My last set of Sofle key plates it looked like the corners of the keyholes were drilled out, and then routed between the corners. Since the switch plates have way less holes than the actual pcb, i suspect that the size of the holes on the switch plates requires a different manufacturing method, hence the extra cost. I haven't the foggiest as to what that size threshold is though. Did you get charged on your last run of Junco?

I started using that template repo because OSHPark directed me there a few months back when i asked them for an updated template -  I really should have checked.

As i was putting together the PNP file and the BOM, i learned a few things that i think are worth mentioning:

- The LED footprints were set to be on the back, which makes it easier when creating the PCB layout. When generating the PNP file, the footprint defaults to front orientation. This caused the PNP to put them on the front. I switched the footprint to default to the front, and then on the pcb flipped sides, so the PNP knew to put them on the back. (I'm not sure if the way i explained that made sense?)

- From what I'm reading about PNP setup, the [orientation of the part in the reel](https://support.jlcpcb.com/article/99-does-the-red-dot-means-pin-1-in-the-placement-previewer) needs to be accounted for. The SK6803s are oriented with the lense down in the reel, so the PNP machine can't install them flipped for the underglow unless they are installed on the front of the board. (Or hand-soldered). Would it be better to compromise with front of the board soldering, or look for an upward facing SMD LED led like [WS2812](https://keeb.io/collections/diy-parts/products/individual-rgb-leds-sk6812-ws2812b-compatible)? (This is probably out of scope for this key orientation adjustment, but probably worth thinking about for future iterations?)

- I suspect the LED's footprints that are offset from the axis for easy key alignment, they are probably going to muck with the PNP stuff. I think i'll need to pull those back to centered 0,0, then move them in the pcb layout. (Not 100% on this, may just send it out and see if jlc kicks it back?)

- I notice the [pico clones from aliexpress](https://www.aliexpress.us/item/3256803742243554.html?spm=a2g0o.productlist.main.1.51a438948Santt&algo_pvid=0f4e0197-548f-4491-9c86-d8d189598348&algo_exp_id=0f4e0197-548f-4491-9c86-d8d189598348-0&pdp_npi=3%40dis%21USD%212.93%212.37%21%21%21%21%21%402102176616841947805498438d077a%2112000029798464230%21sea%21US%210&curPageLogUid=aSonXGH4PJHO) have big ol LEDs on them. Have you tried to make use of them as part of the underglow?

- I tried incorporating the level shifter into another project I'm working on - the soldering was difficult. (I melted the first, and ended up drag soldering the second). According to [this thread](https://www.reddit.com/r/olkb/comments/133gbk6/is_it_possible_to_setup_rgb_matrix_using_rp2040/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button), the  sk6812 work without a level shifter, even though they are out of spec. I think removing the level shifter, along with using SK812's and limiting the max output via QMK would make this board more accessible/adoptable, and support the 'easy to source' design philosophy.  During development, did you try omitting the shifter? Do you think this is worth pursuing?

**Comment by daneski13** [comment]
Looking good!

I've gotten charged extra for each run, the reason being having edge cut "islands"/slots in the PCB, I suspect switch plates would have the same problem. It's documented as a [routing fee](https://support.jlcpcb.com/article/62-what-cases-will-be-charged-of-extra-cost) on their website, I wasn't sure originally if the PCB would meet the "too many slots" criteria, but it does. I've heard that on occasion the rule isn't enforced but I have not been so lucky.

A charge for holes is interesting as they only charge if you have more than 100,000 holes per square meter, that keyboard must be drilling an insane number of holes.

PNP reel placement is not something I was aware of nor did I consider that being an issue. Definitely makes since that the machine wouldn't be able place things upside down relative to the reel. The only reason the underglow was soldered on the backside was for consistency. Going frontside would probably help with routing as well, also will give me more motivation to fix the case files.

Re: WS2812s.
No keyboard I'm aware of uses WS2812s for per-key lighting, the reason being the insane current draw, 5050 can draw up to 60mA and 3535 is up to 45mA iirc **per LED**. For reference the Pico itself draws maximum of 80mA and we've only got 500mA to work with on the Pico's USB 2.0. This is also why I highly recommend the SK6803 (3mA) over the SK6812 (12mA). Unfortunately the 3mA variant isn't as prolific as the 12 and JLC doesn't offer it atm, if they ever have. Also, WS2812 color output is voltage dependent which causes some issues.

Not having the footprint offset would make things more annoying in design, curious if JLC would kick that back, if they do I'd be happy to fix that since I've got a little script that will space things for me, think it's actually in the repo somewhere.

I did look into doing something with the LED at one point, not entirely sure why I abandoned that but I think it's because not all the generic clone manufactures have them, only 2 do (clone [spreadsheet](https://docs.google.com/spreadsheets/d/1LPjy6F5lHfUkmsrM5zlZmc5auYy5YBakW8Awe6hYFWo/edit#gid=0). Also, QMK doesn't like merging fancy extras these days and trying to drive that LED would involve leveraging some drivers deep within QMK. I implemented complete EEPROM syncing between the sides of the split in my PR (i.e. change RGB settings or keymap in VIA or the default layer, then plug-in other half of the split and it'll persist between sides) but the core team wasn't a fan (understandable reasons I must admit). Instead they suggested a core change and had me strip a lot of my custom code out, unfortunately I have been way too busy to try and coordinate and work on a core change proposal/implementation.

Level shifter.
The level shifter is definitely a massive pain to solder, requires very thin solder wire, a small tip, and a lot of finesse. I did try no level shifter once on the SK6803s and it didn't work, but I don't remember if I adequately tested at different brightness levels. I'll look into that in the morning. I have my doubts that the 03 variant will work at all considering at 3.3V we're talking almost a tenth of a watt of power draw, with the 12 it'd be around half a watt. Additionally, the 12's signal flip threshold is 3.4V while the 03's is 3.5V, not surprised that 0.1V below spec works (although I doubt with 100% reliability). I'm sure there's some room in that spec from the manufacturer but I have serious doubts about 0.2V below spec working.

Kinda funny to see my repo mentioned on reddit when I have yet to make any posts about it (saving that for rev2 with more kinks worked out), actually I'm surprised you've stumbled across it.

Level shifter definitely eats into the accessibility of sourcing and ease of soldering, drag soldering is the way I've been doing it and is probably the best method given how close those dang pins are. The shifter was a 1 extra part + $4 compromise to ensure things work properly. Tradeoff to not have to compromise LED brightness nor rely on out of spec voltages working properly.

**Comment by daneski13** [comment]
Attempted to test no level shifter by shorting the data transfer pads, at lower brightness levels the LED's do stay on, however they will not change color and just stay frozen in their previous state. At max brightness the LEDs just shut off. Not exactly a perfect test though and SK6812s may have different behavior. 

I'd err on keeping the level shifter as the "recommended" option but maybe adding some close together pads that could be easily shorted to bypass the need for a level shifter would be a compromise? Especially since RGB is very much an Optional thing, loads of people prefer not to have it

**Comment by JellyTitan** [comment]
I'm starting to think that extra-routing charge is completely arbitrary.

I think you're right, sticking with the SK6803 is the way to go. I completely forgot about the current restrictions when i brought up the alternate under-glow option. I'm going to leave the under-glow pads on the underside and solder those on manually.

I cribbed your level shifter design for a [Sofle pico variant](https://github.com/JellyTitan/Sofle-V3b/blob/main/sofle_v3_build_guide.md) I'm working on. I flashed it with Junco QMK, and the LED's on the Picos lit up along with the SK6803's. It was completely unexpected, but I'm kinda excited it worked without anything special. I tweaked the qmk config and reflashed, and the LED's turned off. I think there might be native support, or just a freak accident. 

That spreadsheet is super helpful - i'm now taking Pico LED orientation into consideration on other designs.

Thanks for giving the level shifting bypass a try. I added a level shifter bypass jumper pad. I'll probably pull the 03's off one set and pop in the 12s to see what happens.

I think my next step is to get the BOM/PNP files dialed in, and then place an order. Hoping i'll have time for that this week.

I'm pretty good with [cases](https://www.printables.com/model/299488-iris-rev6a-keyboard-case). With Sofle/Corne i usually see the pcb keyplates instead of 3d printed cases. Are there any cases that you would recommend for inspiration?

**Comment by daneski13** [comment]
Awesome!

Perhaps I'm misinterpreting. By underglow you mean the LED's facing the floor in normal use I assume? Like I said previously only had them on the backside for consistency since everything else was soldered on the back side. Absolutely could have the pads top side, lens facing down, to be compatible with PNP if that would be a better way of doing it.

Also not to say SK6812s are unsupported, just having them at max brightness may cause issues since all of them at full blast would draw ≈900mA.

Feel free to add whatever you want to the case folder, I based mine somewhat off of [Iris'](https://github.com/keebio/iris-case). But it has some issues (need to move the "lip" and the cutout holes 1.5mm down). Yeah, typically people order an aluminum switch plate from the PCB manufacturer but I'm a cheap bastard.

Another thing to note is that the components being soldered on the backside has some challenges, mainly that it makes a middle layer more or less mandatory, so I decided to enclose the entire PCB with a switch plate and bottom "bowl" that has a lip where the PCB rests. Also that way only 4 screws are needed for each side. I'd recommend taking a look at the the stl files in the case folder.

Im happy to have any functional case design in the repo since I plan to allow community case options to be merged.

**Comment by JellyTitan** [comment]
Thanks for clarifying! 

I did move the underglow LED pads to the topside, that sort of poka-yoke's the underglow installation. 

Today i made it to the JLC ordering placement phase. I learned some new stuff that impacts the pcb layout that I wanted to note here before I forget.
Since the SK6803's are not stocked, they require pre-order. The pre-orders have minimum quantities, and since there's 3 separate footprints for the same part, I'd have to make three separate pre-orders hitting the minimum quantities. I'm going to go back and set all the LED's to use the same footprint, and then use the "move exactly" shortcut to put them back in position.

I also found the KiCad generated BOM & PNP files aren't JLC ready, so those need to be manually updated.

**Comment by daneski13** [comment]
If you want to do PNP and it't not a large to medium size run I'd recommend just using the in-stock SK6812s since there are some fees associated with ordering parts. It would appear they lowered the fees since last time I checked though.

**Comment by daneski13** [comment]
Ok revise, they only charge 15% which isn't actually bad (at least that's all i kind find on the subject). They used to charge a flat $300 pickup fee and some sort of storage costs as well.

**Comment by JellyTitan** [comment]
I haven't seen those fees before - but it wouldn't surprise me in the slightest. 

It looks like they have an option to build 2 of 5 boards. I'm gonna go try that route to make it easier to build one with the SK6812s. 
The hotswop sockets are considered irregular, so those would require "standard" pcb assembly instead of "economy". ~$8 vs ~$30, but upgrading to 'standard' allows for double sided assembly, not sure if i want to go that route. (I really don't mind soldering those).

 I used the parts purchase process to order enough SK6803s for 2 boards. The pricing on those changed after placing the initial order - there's a ton of unexpected pricing swings. I'm waiting for that purchase to finalize before i can go any further.
 
 I've been screen-capping as i go to build out an ordering guide. 
 
 It's been a weird experience so far

**Comment by JellyTitan** [comment]
Quick update. The SK6802s finally came in, so i placed an order. It should be a few weeks now. Fingers crossed!

**Comment by JellyTitan** [comment]
JLC is asking for another ~$30USD. I expected the "too many holes up charge", but the 'too many designs" charge was unexpected. Did you get that last order?

I'm going to try and cancel the order and rework with a revised LED footprint to see if I can't avoid the holes charge. Is there a particular footprint you had in mind? I haven't come across an LED footprint like that in the wild, but i do have some [Kailh scissor switch footprints](https://github.com/shikamiya/kicad-footprint-kailh-pg1425-x-switch/tree/master) that make square holes out of drills, so I have a solid reference to start from.

For the "too many designs" error, i think a manufacturing frame like the [Corne Cherry](https://github.com/foostan/crkbd/blob/main/corne-cherry/doc/v3/buildguide_en.md) might do the trick. (Really not sure though - this feels like another arbitrary fee).

> You need to pay additional 27.12 for your order. Junco-5-21-2023_v7_Y51【4539602A_Y51】
> Reason:
> 1.The order info shows that there is only one design , but actually, there are 2 different designs in your file, so there will be an extra cost for it if you want to make it as show in your file.Please kindly choose the correct designs when you place your order next time.
> 2.There are too many small slots in your file , it will take too much time to get it finished during the routing process.

**Comment by daneski13** [comment]
Apologies for my slow response. 

I did not have that fee, I just selected "2 designs" on the quote page and it wasn't a problem.

There was not a particular footprint i had in mind for the LEDs since I created the footprint myself originally, I was thinking to keep it simple with 5 drill holes. 1 larger one in the centre and 4 for the corners.

**Comment by JellyTitan** [comment]
Thanks! I got the holes setup - i started before i saw your comment, so it's a 7 hole layout based on the pg1425. I'll revise if they throw it back with an extra fee. I'm working on the frame still. Hoping to get it back into production this week.

**Comment by daneski13** [comment]
Awesome!

**Comment by JellyTitan** [comment]
The new build works as expected. I'm updating the docs to submit a PR. 
For versioning - would you like to go with V1.1 or V2.0? (I'm thinking 1.1 because the form factor is the same - but adding a handedness pin would suggest V2?)

**Comment by daneski13** [comment]
Great to hear!! I agree that V1.1 would be appropriate if no updates to QMK is necessary.

**Comment by azhizhinov** [comment]
Hello.
Thanks for your efforts.
Based on your both work, I've made my own design.
Universal PCB for both hands.
What do you think?
Do you want me to push my work into your repo?
Thanks in advance.
![20230901 AZHIZHINOV JUNCO 00](https://github.com/daneski13/Junco/assets/13044908/5fb7a22e-4fc2-4c37-98d3-29c5a976c00d)

**Comment by JellyTitan** [comment]
Looks great! 
I'd like to keep my revision as the 1.1, because i think your double-sided board would be better suited to 2.0. 
I'll try to finish the 1.1 docs tomorrow and then submit a PR. 
I cloned a bunch of the footprints from the submodules and tweaked them a bit, so I'd like to put 1.1 in it's own subfolder. 
[Sofle](https://github.com/josefadamcik/SofleKeyboard) has a pretty good structure for the variant breakouts in folders.

**Comment by daneski13** [comment]
Appreciate the work @azhizhinov! Originally I was against doing a double sided board since it can make the soldering job somewhat more error-prone. However, if that's what people are leaning towards for simplicity in the ordering process I'm not necessarily opposed.

Is it cheaper to go with a single PCB or to stick with a panelized board?  Also, with this single board design how would one go about placing the controller onto the board given that there is not 2 different through-holes for the Pico depending on left/right? Wouldn't one side be forced to have the Pico on the opposite side of the board or upside-down to match the connections?

**Comment by azhizhinov** [comment]
Hello.
It might be differences between countries, but - yes, single PCB is cheaper comparing to a panellized twins in most cases.
2 designs per board are more expensive from the start.
Yes, single PCB can be challenging, I'm not pushing this design hard.
And now I'm thinking pushing this design in to your repo is not a good idea, cos you'll be receiving odd responsibility for my possible errors. :-)
Yes, the Pico placement can be inconvenient for someone, but if the keyboard will be wearing a case, when it will be no problem, from my point of view.
But I can provide you with sources, if you want, and you can review them and make a decision, or make some improvements. :-)

**Comment by JellyTitan** [comment]
@daneski13 
V1.1 is well developed enough that I'll be submitting a PR. I'd like to close this thread, as it seems to have gone a bit off topic.
